### ISSUE TITLE
No wagons

### ISSUE THREAD

**Issue by stefanct** [spnda/Austrian-Trains#4]
Hi,
I have re-installed openttd (debian's 1.6.1 which is a bit older) after a long hiatus and have this öbb grf installed as only addon. When starting a new map (1950) I can buy the ÖBB 16 and 5042. However, there are no wagons available to pair with either (expected for the 5041 I guess). Is this a bug or what do I do wrong?

**Comment by spnda** [comment]
At this time, there are no wagons available at that time, they come later around 1995. This is still kind of a pre release to the full version. There's still more to come though!

**Comment by stefanct** [comment]
I see, thanks. Would be nice if this would be mentioned at least in the readme since it was rather surprising.
